### ISSUE TITLE
Explain how to use the config

### ISSUE THREAD

**Issue by jgeerds** [coreyoconnor/nix_configs#1]
Could you please update your _README.md_ and explain how to build the different machine settings? (e.g. `nixos-rebuild ....toast`)

I don't want to use your personalised settings but I'm interested in your "repository design" for my own configuration settings.

**Comment by coreyoconnor** [comment]
thanks for the request!
Contributing the repository design to the community is a great idea.

I've added two things:
1. a bit more in the readme
2. scripts: ./bin/build and ./bin/switch

which perform a build and switch using this repository.

I'm not resolving this issue yet. The docs and scripts are incomplete. Mostly just letting you know there has been some progress haha.

**Comment by coreyoconnor** [comment]
I ended up switching to colmena. Those docs cover how to use that system. For my own configs I put together a tour: https://www.youtube.com/watch?v=pKVf9x29djs

Which hopefully covers these questions. :)
